### ISSUE TITLE
Make sure to trigger tests for external contributions/PRs

### ISSUE THREAD

**Issue by ganesh-k13** [mkirchner/gc#45]
Hey @mkirchner, is there a provision like Travis where we can run the CI for all PRs, it's easy to see if we are breaking anything.

_Originally posted by @ganesh-k13 in https://github.com/mkirchner/gc/pull/33#issuecomment-569397018_

We can see that tests are triggered for your PRs like # 43, but in cases such as mine or ssrlive's, it does not.

Am I not creating a PR in a proper fashion, or are we missing something? Sorry if this is a basic question as I am new to github workflows

**Comment by mkirchner** [comment]
Hi @ganesh-k13 , I am new to github actions as well, but I think the reason why the tests are not triggered is that you should trigger them yourself when you make a PR against your own fork.

In other words, the workflow should probably be: (1) make a fix in a separate branch; (2) open a PR in your own fork (that should trigger the tests in your account); (3) make a separate PR against my repo.

What I should probably do is to open up a `devel` branch as the initial merge target so that we don't break `master` if an external PR is not ready to go in...

**Comment by ganesh-k13** [comment]
Thanks for response @mkirchner, I'll try it on one of my repos, and update here.

**Comment by mkirchner** [comment]
Closing this as it seems to have been resolved.
