### ISSUE TITLE
About heap address space

### ISSUE THREAD

**Issue by ssrlive** [mkirchner/gc#49]
I find that we can find out the heaps beginning address and size of a process. 
In windows, it can from this [sample](https://docs.microsoft.com/zh-cn/windows/win32/memory/getting-process-heaps). It can retrive all the heap's start addresses in the memory.
In unix, it's seams that we can from `sbrk(0)`. see [this article](https://blog.holbertonschool.com/category/hack-the-virtual-memory/) 

depends this information, in `gc_mark_alloc` function, we can judge the pointer value if a real heap pointer or not.

This can speeds up scanning. Or avoid a lot of complaints from valgrind.

**Comment by sgf** [comment]
PR maybe ?

**Comment by mkirchner** [comment]
Hi @ssrlive , it seems that the request for optimization is not gaining traction here right now. I am closing this for now since I am considering it an optimization beyond the original idea of an educational GC implementation. That said, I'd be absolutely happy to check a PR if someone wants to put the work in. Thanks!
